export type BriefSectionConfig = {
  eyebrow: string;
  title: string;
  description: string;
  fullRoute: string;
  fullLabel: string;
  calloutTitle: string;
  calloutDescription: string;
  calloutCta: string;
};

export const ADMIN_BRIEF_SECTIONS = {
  orders: {
    eyebrow: "Orders",
    title: "Orders",
    description: "Recent volume and how many orders still need fulfillment.",
    fullRoute: "/orders/full",
    fullLabel: "Open order list",
    calloutTitle: "Orders",
    calloutDescription: "Search orders, change status, and open one for line items and payment.",
    calloutCta: "Open order list",
  },
  vendors: {
    eyebrow: "Vendors",
    title: "Vendor base overview",
    description: "Active sellers, suspension risk, and marketplace supply at a glance.",
    fullRoute: "/vendors/full",
    fullLabel: "Open full vendor directory",
    calloutTitle: "Review every vendor in detail",
    calloutDescription: "Performance metrics, store counts, sales totals, and account moderation for every vendor.",
    calloutCta: "Open full vendor directory",
  },
  vendorApplications: {
    eyebrow: "Vendor applications",
    title: "Onboarding queue overview",
    description: "Pending approvals and application pressure on the vendor pipeline.",
    fullRoute: "/vendor-applications/full",
    fullLabel: "Open full application queue",
    calloutTitle: "Process every application",
    calloutDescription: "Review business details, store proposals, uploaded assets, and approve or reject submissions.",
    calloutCta: "Open full application queue",
  },
  stores: {
    eyebrow: "Stores",
    title: "Store footprint overview",
    description: "Active storefronts, drafts, and suspended stores across the marketplace.",
    fullRoute: "/stores/full",
    fullLabel: "Open full store directory",
    calloutTitle: "Manage every storefront",
    calloutDescription: "Create stores, update status, and open full profiles with products, stats, and vendor context.",
    calloutCta: "Open full store directory",
  },
  products: {
    eyebrow: "Products",
    title: "Products",
    description: "Listings on the platform and how many need approval.",
    fullRoute: "/products/full",
    fullLabel: "Open product list",
    calloutTitle: "Products",
    calloutDescription: "Add listings, approve pending items, and update status.",
    calloutCta: "Open product list",
  },
  finance: {
    eyebrow: "Finance",
    title: "Treasury overview",
    description: "Platform balances, commission, and payment flow at a glance.",
    fullRoute: "/finance/full",
    fullLabel: "Open treasury command center",
    calloutTitle: "Full treasury intelligence",
    calloutDescription: "Balances, payment transactions, ledger entries, liabilities, and payout exposure in one place.",
    calloutCta: "Open treasury command center",
  },
  payouts: {
    eyebrow: "Payouts",
    title: "Vendor withdrawal queue",
    description: "Review, approve, reject, and mark vendor payout requests from one queue.",
    fullRoute: "/payouts",
    fullLabel: "Open withdrawal queue",
    calloutTitle: "Process every withdrawal",
    calloutDescription: "Review payout accounts, transfer references, wallet balances, and admin notes for each request.",
    calloutCta: "Open withdrawal queue",
  },
  returns: {
    eyebrow: "Returns",
    title: "Returns desk overview",
    description: "Open cases, refunds, and exchange volume across customer support.",
    fullRoute: "/returns/full",
    fullLabel: "Open full returns desk",
    calloutTitle: "Resolve every return case",
    calloutDescription: "Evidence, customer context, linked orders, and resolution workflow for all return requests.",
    calloutCta: "Open full returns desk",
  },
  reviews: {
    eyebrow: "Reviews",
    title: "Review moderation overview",
    description: "Community feedback volume, hidden content, and average ratings.",
    fullRoute: "/reviews/full",
    fullLabel: "Open full review moderation",
    calloutTitle: "Moderate every review",
    calloutDescription: "Product context, shopper details, ratings, and hide/restore controls for all reviews.",
    calloutCta: "Open full review moderation",
  },
  vouchers: {
    eyebrow: "Vouchers",
    title: "Promo campaigns overview",
    description: "Active vouchers, redemptions, and discount exposure across checkout.",
    fullRoute: "/vouchers/full",
    fullLabel: "Open full voucher studio",
    calloutTitle: "Manage every campaign",
    calloutDescription: "Create campaigns, set limits, track redemptions, and audit discount totals.",
    calloutCta: "Open full voucher studio",
  },
  markets: {
    eyebrow: "Markets",
    title: "Markets overview",
    description: "Geographic marketplace coverage and active location count.",
    fullRoute: "/markets/full",
    fullLabel: "Open full markets registry",
    calloutTitle: "Manage every market",
    calloutDescription: "Create, edit, and assign markets across the ODOS marketplace footprint.",
    calloutCta: "Open full markets registry",
  },
  categories: {
    eyebrow: "Categories",
    title: "Categories",
    description: "Top-level catalog groups and how many are active.",
    fullRoute: "/categories/full",
    fullLabel: "Open category list",
    calloutTitle: "Categories",
    calloutDescription: "Add categories, edit subcategories, and enable or disable them.",
    calloutCta: "Open category list",
  },
  promoBanners: {
    eyebrow: "Promo banners",
    title: "Promo banners overview",
    description: "Home-screen marketing assets and active banner count.",
    fullRoute: "/promo-banners/full",
    fullLabel: "Open full banner studio",
    calloutTitle: "Design every banner",
    calloutDescription: "Creative assets, schedules, CTAs, and placement for all promo banners.",
    calloutCta: "Open full banner studio",
  },
  flashSaleEvents: {
    eyebrow: "Flash sale events",
    title: "Flash events overview",
    description: "Live and scheduled flash sales across the marketplace.",
    fullRoute: "/flash-sale-events/full",
    fullLabel: "Open full flash sale calendar",
    calloutTitle: "Run every flash event",
    calloutDescription: "Event schedules, featured product rosters, and status for all flash sales.",
    calloutCta: "Open full flash sale calendar",
  },
  merchandisingCampaigns: {
    eyebrow: "Campaigns",
    title: "Merchandising campaigns overview",
    description: "Seasonal and featured marketplace campaigns for shopper discovery.",
    fullRoute: "/merchandising-campaigns/full",
    fullLabel: "Open campaign studio",
    calloutTitle: "Run every campaign",
    calloutDescription:
      "Schedule campaigns, assign products/categories/stores, and control home discovery.",
    calloutCta: "Open campaign studio",
  },
  supportChats: {
    eyebrow: "Support chats",
    title: "Support inbox overview",
    description: "Open threads, admin workload, and unread message pressure.",
    fullRoute: "/support-chats/full",
    fullLabel: "Open full support inbox",
    calloutTitle: "Handle every conversation",
    calloutDescription: "Full inbox with thread metadata, messages, status updates, and store context.",
    calloutCta: "Open full support inbox",
  },
  notifications: {
    eyebrow: "Notifications",
    title: "Admin signals overview",
    description: "Unread alerts and notification volume across the platform.",
    fullRoute: "/notifications/full",
    fullLabel: "Open full notification feed",
    calloutTitle: "See every signal",
    calloutDescription: "Complete notification history with type filters and read-state management.",
    calloutCta: "Open full notification feed",
  },
} satisfies Record<string, BriefSectionConfig>;
